package com.rf1m.image2css.cmn.ioc;

public enum BeanType {
    arrayList,
    base64Encoder,
    basicParser,
    byteArray,
    commandLineParametersParser,
    commandLineRunner,
    commandLineRunnerOutputManager,
    commandLineRunnerValidator,
    consoleOutput,
    conversionFilenameFilter,
    cssClass,
    cssOutput,
    defaultImageConversionService,
    defaultPrintStream,
    dimension,
    exceptionHandler,
    file,
    fileArray,
    fileInputStream,
    fileUtils,
    fileWriter,
    htmlOutput,
    imageIcon,
    immutableParameters,
    optionCssFile,
    optionHtmlFile,
    optionImageFile,
    optionImageTypes,
    optionSyso,
    options,
    pair,
    helpFormatter,
    properties,
    reportOutput,
    resourceBundle,
    set,
    string,
    stringArray,
    stringBuffer,
    supportedImageTypes,
    systemWrapper,
    url

}
